#!/bin/sh

_dmenu_path() {
    cat <<EOF
xdg-open
xdotool type
${TERMINAL:-st} ${EDITOR:-vi}
cp -nrv
ln -sv
mv -nv
rm -dv
mkdir -pv
cd
EOF
dmenu_path | sed '/^\(xdg-open\|cp\|ln\|mv\|rm\)$/d'
}

dice() {
    for last; do :; done
    [ -d "$last" ] && cd "$last" || cd "$(dirname "$last")"
    IFS=' 	'
    prog="$( _dmenu_path | dmenu -l 9 -p "Pass $# files as arguments to" | sed q )"
    [ -z "$prog" ] && exit 1
    if [ -n "$prog" ]; then
        case "$prog" in
        rm|rm[[:space:]]*)
            polar="$(printf '%s\n' no yes | dmenu -p "Remove $# files?" -sb '#ff5370')"
            [ "$polar" = yes ] && $prog -- "$@"
            ;;
        mv|mv[[:space:]]*)
            last="$( pathmenu -i -l 20 -p "Move $# files to" | sed q )"
            [ -z "$last" ] && exit 1
            [ -n "$last" ] && $prog -- "$@" "$last" 2>&1
            ;;
        cp|cp[[:space:]]*)
            last="$( pathmenu -i -l 20 -p "Copy $# files to" | sed q )"
            [ -z "$last" ] && exit 1
            [ -n "$last" ] && $prog -- "$@" "$last" 2>&1
            ;;
        ln|ln[[:space:]]*)
            last="$( pathmenu -i -l 20 -p "Link to $# files from" | sed q )"
            [ -z "$last" ] && exit 1
            [ -n "$last" ] && $prog -- "$@" "$last" 2>&1
            ;;
        *)
            $prog "$@"
            ;;
        esac
    fi | dmenu -l 10 -p 'stdout and stderr' >/dev/null 2>&1
    return 0
}

while :; do
    IFS='
'
    sels="$(pathmenu -i -l 20 "$@")"
    dice $sels || break
done
