.\" pathmenu
.\" Copyright (c) 2019 Gregory L. Chamberlain
.\" Available under the MIT License -- see LICENSE file.
.TH "PATHMENU" "1" "August 2020"
.SH NAME
pathmenu \- browse and select files with dmenu
.SH SYNOPSIS
.B pathmenu
.RB [ \-A | \-F | \-P | \-a | \-d ]
.RB [ -c
.IR command ]
.RB [ -- ]
.SH DESCRIPTION
.PP
.B pathmenu
allows the user to browse the filesystem
and select files
using
.BR dmenu (1).
Selected file paths are written one per line to standard output.
.SH OPTIONS
.TP
.B \-A
Show hidden files except \[oq].\[cq] and \[oq]..\[cq].
See also
.BR \-a .
.TP
.B \-F
Append forward slashes to directories, analogous to the
.B \-p
option for
.BR ls (1).
.TP
.B \-P
Resolve symbolic links when changing directories.
See
.BR cd (1).
.TP
.B \-a
Show hidden files.
.IP
When combined with \-A show only
visible files,
\[oq].\[cq] and
\[oq]..\[cq].
.TP
.BI -c command
Use
.I command
as the dynamic menu command instead of the default
which is \[oq]\f[C]dmenu -p "$PWD"/\f[R]\[cq].
.IP
.B Warning:
This command is reinterpretted by the shell using eval(1),
so it possible to execute arbitrary code this way.
.TP
.B \-d
Show only directories.  Combines predictably with
.B \-A
and
.BR \-a .
.SH BUGS
.PP
File names are piped into
.BR dmenu (1)
one per line
and so file names that contain new line characters
cannot be listed safely;
therefore they are omitted.
A solution might be to encode file names before piping them into dmenu,
and decode file names selected or written by the user,
but this is not (yet) implemented.
.SH AUTHOR
Gregory Chamberlain <greg\[at]cosine.blue>.
.SH SEE ALSO
.BR dicemenu (1),
.BR dmenu (1)
.BR fzf (1),
.BR rofi (1)

