.\" pathmenu
.\" Copyright (c) 2019-2020 Gregory L. Chamberlain
.\" Available under the MIT License -- see LICENSE file.
.TH "PATHMENU" "1" "August 2020"
.SH NAME
pathmenu \- browse and select files with dmenu
.SH SYNOPSIS
.B pathmenu
.RB [ \-AadFfhnP ]
.RB [ \-c
.IR command ]
.RB [ \-p
.IR pattern ]...
.RI [ directory ]
.SH DESCRIPTION
.PP
.B pathmenu
allows the user to browse the filesystem and select files using
.BR dmenu (1)
or a suitable replacement.
Selected file names are written one per line to standard output in
absolute form.
.PP
.B pathmenu
begins in
.I directory
or else the working directory.
.PP
The empty selection will cause
.B pathmenu
to return to the directory in which it began.
.PP
For some programs such as
.BR rsync (1),
the presence of a forward slash immediately following the name of
a directory can be meaningful and affect program behaviour.
With the exception of the working directory,
directories selected in
.B pathmenu
are printed without the trailing slash; so, the only way to have
.B pathmenu
include the trailing slash is by descending into the desired directory
and entering \f[C].\f[R] (dot)
or \f[C]./\f[R] (dot-slash).
.PP
Selecting a single hyphen (\-) will navigate to the previous working
directory ($OLDPWD).
.SH OPTIONS
.TP
.B \-A
List all hidden files except
\f[C].\f[R] (dot)
and
\f[C]..\f[R] (dot-dot).
.IP
Combined with
.B \-a
the effect is inverted so that
\f[C].\f[R] and
\f[C]..\f[R]
are the only hidden files listed.
.TP
.B \-a
List hidden files.
.TP
.BI "\-c " command
Use
.I command
as the dynamic menu command instead of the default
which is \f[C]dmenu \-p "$PWD"/\f[R].
.TP
.B \-d
List only directories.
.TP
.B \-f
List only regular files (not directories).
.TP
.B \-h
Output a usage message and exit.
.TP
.B \-n
List matches that refer to non-existent files.
.TP
.B \-F
Append a forward slash to each directory name listed.
.TP
.B \-P
Resolve symbolic links when changing directories.
See the same option in
.BR cd (1).
.TP
.BI "\-p " pattern
List files that match the pattern according to
.BR glob (7).
Can be specified multiple times.
Disables
.B \-A
and
.BR \-a .
With no
.BR \-A ,
.B \-a
nor
.B \-p
the default pattern is * (asterisk), matching all visible files.
.SH BUGS
.PP
File names are piped into
.BR dmenu (1)
one per line
and so file names that contain new line characters
cannot be listed safely;
therefore they are omitted.
A solution might be to encode file names before piping them into dmenu,
and decode file names selected or written by the user,
but this is not (yet) implemented.
.SH AUTHOR
Gregory Chamberlain <greg\[at]cosine.blue>.
.SH SEE ALSO
.BR dicemenu (1),
.BR dmenu (1)
.BR fzf (1),
.BR rofi (1)
