.TH "PATHMENU" "1" "December 2019"
.SH NAME
pathmenu - browse directories and select files with dmenu
.SH SYNOPSIS
\fBpathmenu\fR [\fIOPTION\fR]... [\fIDIRECTORY\fR]...
.SH DESCRIPTION
.PP
\fBpathmenu\fR  allows the user to select any number of files by
recursively browsing directories using \fBdmenu\fR(1).
.PP
With no \fIDIRECTORY\fR, start in the working directory.
Selections are written to standard output.
.SH EXAMPLES
.PP
Interactively move files (use with care):
.IP
.nf
\fC
IFS=\[aq]
\[aq] mv -i -- $(pathmenu -p Source) $(pathmenu -p Destination | sed q)
\fR
.fi
.PP
Suggest only directories:
.IP
.nf
\fC
pathmenu -d
\fR
.fi
.PP
Browse \[ti]/src/foo/, including hidden files, and edit the selected
files:
.IP
.nf
\fC
IFS=\[aq]
\[aq] $EDITOR $(pathmenu -a \[ti]/src/foo)
\fR
.fi
.PP
See also \fBdicemenu\fR(1) for a (very) basic file manager built on
pathmenu.
.SH AUTHOR
Written by Gregory Chamberlain <greg\[at]cosine.blue>.
.SH SEE ALSO
.BR dicemenu (1),
.BR dmenu (1)
