#!/bin/sh -eu
# dicemenu
# Copyright (c) 2019 Gregory L. Chamberlain
# Available under the MIT License -- see LICENSE file.

IFS='
'

dice() {
    case $# in
        0) return 1 ;;
        1) p=${1##*/} ;;
        2) p="${##*/}, ${2##*/}" ;;
        3) p="${##*/}, ${2##*/}, ${3##*/}" ;;
        *) for last do :; done
           p="${1##*/}, ${2##*/}, …, ${last##*/}"
    esac
    cmd=$(dmenu_path | dmenu -p "$p") &&
        eval "$cmd"
}

while dice $(pathmenu "$@"); do :; done
