#!/bin/sh -ef
# dicemenu
# Copyright (c) 2019 Gregory L. Chamberlain
# Available under the MIT License -- see LICENSE file.

IFS='
'

: "${TERMINAL:=xterm}" "${PAGER:=less}" "${VISUAL:=${EDITOR:=vi}}"

# shellcheck disable=2016
lscmd() {
    printf '%s "$@"\n' \
        "$TERMINAL -e $PAGER" \
        "$TERMINAL -e $VISUAL"

    if [ $# -eq 1 ]; then
        fmt='$1'
        printf 'ln -s $1 "$(dmenup)"\n'
    elif [ $# -gt 1 ]; then
        fmt='"$@"'
        printf 'ln -s "$@" "$(dmenup -d)"\n'
    fi

    printf "%s $fmt\\n" rm
}

dice() {
    case $# in
        0) return 1 ;;
        1) p=${1##*/} ;;
        2) p="${1##*/}, ${2##*/}" ;;
        3) p="${1##*/}, ${2##*/}, ${3##*/}" ;;
        *) for last do :; done
           p="${1##*/}, ${2##*/}, …, ${last##*/}"
    esac
    cmd=$(lscmd "$@" | dmenu -l 9 -p "$p") &&
        eval "$cmd"
}

# Word splitting is safe and intended here.
# shellcheck disable=2046
while dice $(dmenup "$@"); do :; done
