#!/bin/sh -euf
# dicemenu
# Copyright (c) 2019 Gregory L. Chamberlain
# Available under the MIT License -- see LICENSE file.

IFS='
'

lscmd() {
    #printf '%s\n' \
    cat <<EOF
${TERMINAL:-xterm} -e ${PAGER:-less} "\$@"
${TERMINAL:-xterm} -e ${EDITOR:-${VISUAL:-vi}} "\$@"
ln -s "\$@" "\$(pathmenu -p.. -p.*/ -p*/ -c "dmenu -p 'Symlink \$# files to'")"
EOF
}

dice() {
    case $# in
        0) return 1 ;;
        1) p=${1##*/} ;;
        2) p="${##*/}, ${2##*/}" ;;
        3) p="${##*/}, ${2##*/}, ${3##*/}" ;;
        *) for last do :; done
           p="${1##*/}, ${2##*/}, …, ${last##*/}"
    esac
    cmd=$(lscmd | dmenu -l 9 -p "$p") &&
        eval "$cmd"
}

# Word splitting is safe and intended here.
# shellcheck disable=2046
while dice $(pathmenu "$@"); do :; done
