#!/bin/sh

# shellcheck disable=SC2016,SC1004
pathmenu \
    -p '.*/' \
    -p '.*' \
    -p '*/' \
    -p '*' \
    -c'dmenu -i \
             -l 12 \
             -p "${OLDPWD#${PWD%/}/}/${PWD#${OLDPWD%/}/}"' \
    "$@"
