#!/bin/sh

command -v xdotool && windowid=$(xdotool getactivewindow)

# shellcheck disable=SC2016,SC1004
pathmenu \
    -F \
    -c'dmenu -i \
             -l 12 \
             -w '"${windowid:-root}"' \
             -p "$(
                 case $PWD in
                     ~|~/*) printf %s "~${PWD#~}" ;;
                     *) printf %s "$PWD"
                 esac
             )"' \
    -p.. -p. -p\* \
    "$@"
