#!/bin/sh

# shellcheck disable=SC2016,SC1004
pathmenu \
    -AaF \
    -c'dmenu -i \
             -l 12 \
             -p "$(
                 case $PWD in
                     ~|~/*) printf %s "~${PWD#~}" ;;
                     *) printf %s "$PWD"
                 esac
             )"' \
    "$@"
