#!/bin/sh

# shellcheck disable=SC2016,SC1004
pathmenu \
    -F \
    -c'fzf --preview "[ -d {} ] && ls {} || head -n\$LINES {}" \
           --prompt="$(
               case $PWD in
                   ~|~/*) printf %s "~${PWD#~}" ;;
                   *) printf "%s\n" "$PWD"
               esac
           )/"' \
    -p.. -p. -p\* \
    "$@"
